name: Tests

on:
  push:
    branches:
      - "1.0"
      - "1.1"
      - develop
  pull_request:

jobs:
  unitTests:
    strategy:
      max-parallel: 6
      matrix:
        operatingSystem: [ubuntu-latest, windows-latest]
        phpVersion: ['7.2', '7.3', '7.4', '8.0']
      fail-fast: false
    runs-on: ${{ matrix.operatingSystem }}
    name: ${{ matrix.operatingSystem }} / PHP ${{ matrix.phpVersion }}
    env:
      extensions: curl, fileinfo, gd, mbstring, openssl, pdo, pdo_sqlite, sqlite3, xml, zip
      key: winter-storm-cache-v1.1.2
    steps:
      - name: Checkout changes
        uses: actions/checkout@v2

      - name: Setup extension cache
        id: extcache
        uses: shivammathur/cache-extensions@v1
        with:
          php-version: ${{ matrix.phpVersion }}
          extensions: ${{ env.extensions }}
          key: ${{ env.key }}

      - name: Cache extensions
        uses: actions/cache@v2
        with:
          path: ${{ steps.extcache.outputs.dir }}
          key: ${{ steps.extcache.outputs.key }}
          restore-keys: ${{ steps.extcache.outputs.key }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.phpVersion }}
          tools: composer:v2
          extensions: ${{ env.extensions }}

      - name: Setup dependency cache
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-scripts

      - name: Setup problem matchers for PHPUnit
        if: matrix.phpVersion == '7.4'
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run tests
        env:
            ENABLE_TEST_ARTIFACTS: 1
        run: ./vendor/bin/phpunit ./tests

      - name: Upload test artifacts
        uses: actions/upload-artifact@v3
        with:
            name: ResizerTest
            path: ./tests/artifacts/ResizerTest/
