name: Tests

on:
  push:
    branches:
      - "1.0"
      - "1.1"
      - develop
  pull_request:

concurrency:
  group: phpunit-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unitTests:
    strategy:
      max-parallel: 6
      matrix:
        operatingSystem: [ubuntu-latest, windows-latest]
        phpVersion: ['8.0', '8.1', '8.2']
      fail-fast: false
    runs-on: ${{ matrix.operatingSystem }}
    name: ${{ matrix.operatingSystem }} / PHP ${{ matrix.phpVersion }}
    env:
      extensions: curl, fileinfo, gd, mbstring, openssl, pdo, pdo_sqlite, sqlite3, xml, zip
      key: winter-storm-cache-v1.2
    steps:
      - name: Checkout changes
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.phpVersion }}
          extensions: ${{ env.extensions }}
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --no-progress --no-scripts

      - name: Setup problem matchers for PHPUnit
        if: matrix.phpVersion == '8.2'
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Run tests
        run: ./vendor/bin/phpunit ./tests

      - name: Upload test artifacts on failure
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
            name: ResizerTest-${{ matrix.operatingSystem }}-PHP${{ matrix.phpVersion }}
            path: tests/artifacts/ResizerTest/
            if-no-files-found: error
